language: objective-c

before_install:
    git clone --depth=1 --branch=master git://github.com/PADL/GSSKit.git PADL/GSSKit
    (cd PADL/GSSKit; sudo xcodebuild install)

xcode_project: CredUI.xcodeproj
xcode_scheme: CredUIBase

notifications:
  email:
    - lukeh@padl.com

