language: objective-c

before_install:
    - git clone --depth=1 --branch=master git://github.com/PADL/GSSKit.git PADL/GSSKit

install:
    - cd PADL/GSSKit
    - sudo xcodebuild install DSTROOT=/
    - cd ../..

xcode_project: CredUI.xcodeproj
xcode_scheme: CredUIBase

notifications:
  email:
    - lukeh@padl.com

